version: "3.9"

name: finaptica-infra

networks:
  finaptica-net:
    name: finaptica-net
    driver: bridge

volumes:
  pg_data: {}
  pgadmin_data: {}

services:
  postgres:
    image: postgres:16
    container_name: finaptica-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: >
      postgres -c shared_preload_libraries=pg_stat_statements
               -c max_connections=300
    ports:
      - "5432:5432"
    networks: [finaptica-net]
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: finaptica-pgadmin
    restart: unless-stopped
    networks: [finaptica-net]
    ports:
      - "5050:80" 
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
